apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    environment: staging
  annotations:
    git-commit: "abc123"
    created-by: "CI/CD"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:1.21
          ports:
            - containerPort: 80